/**
 * AI Provider Contract Interface
 * 
 * This contract defines a stable interface for AI chat providers, enabling the application
 * to switch between different AI services (AWS Bedrock, OpenAI, local models, etc.) without
 * modifying core logic. All AI provider adapters must implement this interface.
 * 
 * The contract follows the Dependency Inversion Principle: high-level application logic
 * depends on this stable interface, while low-level vendor implementations are pluggable
 * adapters that implement the contract.
 */

/**
 * Represents a single message in a conversation
 */
export interface AIMessage {
  /**
   * The role of the message sender
   * - 'user': Message from the end user
   * - 'assistant': Message from the AI assistant
   * - 'system': System-level instructions or context
   */
  role: 'user' | 'assistant' | 'system';
  
  /**
   * The text content of the message
   */
  content: string;
}

/**
 * Represents the response from an AI provider
 */
export interface AIResponse {
  /**
   * The text response from the AI
   * This field is always present and contains the main response content
   */
  text: string;
  
  /**
   * Optional array of image URLs related to the response
   * Images may be generated by the AI or retrieved from external sources
   */
  images?: string[];
}

/**
 * AI Provider interface that all AI service adapters must implement
 * 
 * This interface abstracts away vendor-specific implementation details and provides
 * a consistent API for chat-based AI interactions. Adapters are responsible for:
 * - Handling vendor-specific authentication and configuration
 * - Normalizing vendor responses to match the AIResponse format
 * - Managing conversation context and history
 * - Handling errors and providing descriptive error messages
 */
export interface AIProvider {
  /**
   * Send a chat message and receive a response from the AI
   * 
   * This method handles a single turn in a conversation, optionally including
   * conversation history for context. The provider should maintain conversation
   * coherence when history is provided.
   * 
   * @param message - The user's message text to send to the AI
   * @param systemPrompt - System-level instructions that guide the AI's behavior and personality
   * @param history - Optional array of previous messages for conversation context
   * @returns Promise resolving to an AIResponse with text and optional images
   * @throws Error if the AI request fails or returns invalid data
   * 
   * @example
   * ```typescript
   * const provider = new AWSBedrockAdapter();
   * const response = await provider.chat(
   *   "What is photosynthesis?",
   *   "You are a helpful science teacher.",
   *   [
   *     { role: 'user', content: 'Hello!' },
   *     { role: 'assistant', content: 'Hi! How can I help you today?' }
   *   ]
   * );
   * console.log(response.text); // AI's explanation of photosynthesis
   * ```
   */
  chat(
    message: string,
    systemPrompt: string,
    history?: AIMessage[]
  ): Promise<AIResponse>;
}
